const http = require('http');
const { spawn } = require('child_process');
const path = require('path');

const serverProcess = spawn('node', [path.join(__dirname, '..', 'backend', 'server.cjs')], { stdio: 'ignore' });
serverProcess.on('error', () => {});

function requestPost(urlPath, bodyData) {
    return new Promise((resolve, reject) => {
        const payload = JSON.stringify(bodyData);
        const req = http.request({
            hostname: 'localhost',
            port: 5001,
            path: urlPath,
            method: 'POST',
            headers: {
                'Content-Type': 'application/json',
                'Content-Length': Buffer.byteLength(payload)
            }
        }, res => {
            let data = '';
            res.on('data', chunk => data += chunk);
            res.on('end', () => resolve(JSON.parse(data)));
        });
        req.on('error', reject);
        req.write(payload);
        req.end();
    });
}

async function runTest() {
    await new Promise(r => setTimeout(r, 1000));

    console.log("=== SEEDING DB ===");
    await requestPost('/api/seed-graph', {});

    console.log("\n==================================================================");
    console.log("VERIFICATION 1: Chat Query RBAC Scoping Behavior");
    console.log("==================================================================");

    const targetQuery = "show me cases linked to Md. Rafique across districts";

    // 1A. Investigator in Mysuru (Md. Rafique cases are in Tumkur)
    console.log("\n1A. Investigator (Mysuru District):");
    const invMysuruRes = await requestPost('/api/chat-query', {
        query: targetQuery,
        role: 'investigator',
        district: 'Mysuru'
    });
    console.log("Response Answer:\n", invMysuruRes.answer);

    // 1B. Investigator in Tumkur (Md. Rafique cases are in Tumkur)
    console.log("\n1B. Investigator (Tumkur District):");
    const invTumkurRes = await requestPost('/api/chat-query', {
        query: targetQuery,
        role: 'investigator',
        district: 'Tumkur'
    });
    console.log("Response Answer:\n", invTumkurRes.answer);

    // 1C. Analyst in Mysuru (Cross-district read permissions)
    console.log("\n1C. Analyst (Mysuru - Cross District Read):");
    const analystRes = await requestPost('/api/chat-query', {
        query: targetQuery,
        role: 'analyst',
        district: 'Mysuru'
    });
    console.log("Response Answer:\n", analystRes.answer);

    console.log("\n==================================================================");
    console.log("VERIFICATION 2: Dynamic User Session ID in Chat PDF Header");
    console.log("==================================================================");

    const testUsername = "INSPECTOR_DESHMUKH_7781";
    const pdfRes = await requestPost('/api/report-generator', {
        type: 'chat',
        title: 'SETU Investigation Chat Transcript',
        generated_by: testUsername,
        messages: [
            { speaker: 'user', text: targetQuery },
            { speaker: 'system', text: invTumkurRes.answer }
        ]
    });

    console.log("PDF Report Status:", pdfRes.status);
    console.log("Report Generated By Passed:", testUsername);
    if (pdfRes.pdf_base64) {
        const decoded = Buffer.from(pdfRes.pdf_base64, 'base64').toString('utf8');
        const headerLine = decoded.split('\n').find(l => l.includes('Exported by'));
        console.log("Decoded PDF Header Output Line:", headerLine ? headerLine.trim() : "Header line not found");
    }

    serverProcess.kill();
    process.exit(0);
}

runTest().catch(err => {
    console.error(err);
    serverProcess.kill();
    process.exit(1);
});
